issuer: https://token.actions.githubusercontent.com
subject: repo:jamestelfer/docker-credential-env:environment:release
claim_pattern:
  ref: '^refs/tags/v.*$'

permissions:
  contents: write

repositories:
  - docker-credential-env
