issuer: https://token.actions.githubusercontent.com
subject: repo:jamestelfer/imds-broker:environment:release
claim_pattern:
  ref: '^refs/tags/v.*$'

permissions:
  contents: write

repositories:
  - imds-broker
