issuer: https://token.actions.githubusercontent.com
subject: repo:jamestelfer/sandy:environment:automation
claim_pattern:
  ref: 'refs/heads/main'

permissions:
  contents: write
  pull_requests: write

repositories:
  - sandy
