issuer: https://token.actions.githubusercontent.com
subject: repo:jamestelfer/relic:environment:release
claim_pattern:
  ref: '^refs/tags/v.*$'

permissions:
  contents: write

repositories:
  - relic
