issuer: https://token.actions.githubusercontent.com
subject_pattern: '^repo:jamestelfer/[^:]+:environment:release$'
claim_pattern:
  ref: '^refs/tags/v.*$'
  repository: '^jamestelfer/(dollop|relic|sandy|imds-broker)$'

permissions:
  contents: write

repositories:
  - homebrew-tap
