issuer: https://token.actions.githubusercontent.com
subject: repo:jamestelfer@792299/billy@1351037653:environment:release
claim_pattern:
  ref: '^refs/tags/v.*$'

permissions:
  contents: write

repositories:
  - billy
